services:
  nette:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t www
    environment:
      docker: "true"
      # Add environment variables for MySQL connection
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: nettedb
      DB_USERNAME: nette
      DB_PASSWORD: pass
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: nettedb
      MYSQL_USER: nette
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306" # Optional: Expose MySQL port to host
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge

